version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  # 1. Base de datos para Keycloak
  postgres_iam:
    image: postgres:15
    container_name: postgres_iam
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - app-network

  # 2. Keycloak con tu imagen personalizada (Logo Banco Macro/Gestión)
  keycloak:
    image: gpaulucci/ms_keycloak:latest
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: ${DB_JDBC_URL} # jdbc:postgresql://postgres_iam:5432/keycloak
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak-themes:/opt/keycloak/themes:ro
    depends_on:
      - postgres_iam
    networks:
      - app-network

  # 3. Tu Microservicio de Autenticación (BFF)
  ms_api:
    image: gpaulucci/ms_api:latest
    container_name: ms_api
    environment:
      # URL interna de Docker para el Discovery exitoso
      - KEYCLOAK_AUTH_SERVER_URL=http://keycloak:8080
      - KEYCLOAK_REALM=banco-macro
      - KEYCLOAK_CLIENT_ID=ms-auth-backend
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      # URL que el navegador del usuario usará para volver
      - CALLBACK_URL=http://localhost:3000/auth/callback
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres_iam:5432/db
    ports:
      - "3000:3000"
    depends_on:
      - keycloak
    networks:
      - app-network

  # 4. Frontend servido con Nginx
  ms_frontend:
    image: gpaulucci/ms_frontend:latest
    container_name: ms_frontend
    ports:
      - "80:80"
    depends_on:
      - ms_api
    networks:
      - app-network