name: CI/CD Docker Hub Publish

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive' # <--- ESTO ES LO QUE FALTA
          token: ${{ secrets.GITHUB_TOKEN }} # Para asegurar permisos de lectura

      - name: Force Update Submodules
        run: |
          git submodule update --init --recursive --remote

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push MS_Auth
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ms_auth:latest -f ./MS_Auth/Dockerfile ./MS_Auth
          docker push ${{ secrets.DOCKER_USERNAME }}/ms_auth:latest

      - name: Build and push MS_Frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ms_frontend:latest ./MS_Frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/ms_frontend:latest

      - name: Build and push MS_Keycloak
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ms_keycloak:latest ./MS_Keycloak
          docker push ${{ secrets.DOCKER_USERNAME }}/ms_keycloak:latest
